### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by powermx** [Xacnio/youtube-mp3-rest#3]
Hello!

Thx for your work, it works like a charm, but how could I get the json format ?

**Comment by xacnio** [comment]
Hello,

What does it mean? It's working as a http server. You need to make a request to this http server to get the json format.

```sh
curl -H "Accept: application/json" "http://localhost:80/get?url=video__url"
```

```
GET /get
    Query Parameters:
    - url: Youtube-URL
    - redirect (optional): if is 'true' : redirect to MP3 url after downloading
    - performer (optional): performer for MP3 meta data (default: video author name)
    - title (optional): title for MP3 meta data (default: video title)
```

Also this project is for example purposes and it's out of date. I even don't know if it's still working or not. I recommend to you need to develop it if you will use.
